# Generated by Django 5.0.3 on 2024-03-31 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('patient_name', models.CharField(max_length=20)),
                ('gender', models.CharField(choices=[('WOMEN', 'women'), ('MEN', 'men'), ('OTHER', 'other'), ('GIRL', 'girl'), ('BOY', 'boy')], max_length=10)),
                ('phone', models.IntegerField()),
                ('dob', models.DateTimeField()),
                ('marital_status', models.CharField(choices=[('SINGLE', 'single'), ('MARRIED', 'married'), ('DIVORCE', 'divorce'), ('WIDOW', 'widow')], max_length=10)),
                ('created_on', models.DateField(auto_now_add=True)),
                ('updated_on', models.DateField(auto_now=True)),
            ],
        ),
    ]
